services:
  - type: web
    name: ton-frog-jump
    env: node
    buildCommand: npm ci --include=dev && npm run db:push && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CSS_TRANSFORMER_WASM
        value: "0"
        sync: false
